/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as Api_keysRouteImport } from './routes/api_keys'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as TaskTaskRouteImport } from './routes/task.$task'
import { Route as ProjectsProjectRouteImport } from './routes/projects.$project'
import { Route as ProjectsProjectUsersRouteImport } from './routes/projects.$project.users'
import { Route as ProjectsProjectSettingsRouteImport } from './routes/projects.$project.settings'
import { Route as ProjectsProjectFieldsRouteImport } from './routes/projects.$project.fields'
import { Route as ProjectsProjectDataRouteImport } from './routes/projects.$project.data'
import { Route as ProjectsProjectDashboardRouteImport } from './routes/projects.$project.dashboard'
import { Route as ProjectsProjectAccessRouteImport } from './routes/projects.$project.access'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const Api_keysRoute = Api_keysRouteImport.update({
  id: '/api_keys',
  path: '/api_keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const TaskTaskRoute = TaskTaskRouteImport.update({
  id: '/task/$task',
  path: '/task/$task',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectRoute = ProjectsProjectRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectUsersRoute = ProjectsProjectUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProjectsProjectRoute,
} as any)
const ProjectsProjectSettingsRoute = ProjectsProjectSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProjectsProjectRoute,
} as any)
const ProjectsProjectFieldsRoute = ProjectsProjectFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => ProjectsProjectRoute,
} as any)
const ProjectsProjectDataRoute = ProjectsProjectDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => ProjectsProjectRoute,
} as any)
const ProjectsProjectDashboardRoute =
  ProjectsProjectDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProjectsProjectRoute,
  } as any)
const ProjectsProjectAccessRoute = ProjectsProjectAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => ProjectsProjectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/api_keys': typeof Api_keysRoute
  '/branding': typeof BrandingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/users': typeof UsersRoute
  '/projects/$project': typeof ProjectsProjectRouteWithChildren
  '/task/$task': typeof TaskTaskRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$project/access': typeof ProjectsProjectAccessRoute
  '/projects/$project/dashboard': typeof ProjectsProjectDashboardRoute
  '/projects/$project/data': typeof ProjectsProjectDataRoute
  '/projects/$project/fields': typeof ProjectsProjectFieldsRoute
  '/projects/$project/settings': typeof ProjectsProjectSettingsRoute
  '/projects/$project/users': typeof ProjectsProjectUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/api_keys': typeof Api_keysRoute
  '/branding': typeof BrandingRoute
  '/users': typeof UsersRoute
  '/projects/$project': typeof ProjectsProjectRouteWithChildren
  '/task/$task': typeof TaskTaskRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$project/access': typeof ProjectsProjectAccessRoute
  '/projects/$project/dashboard': typeof ProjectsProjectDashboardRoute
  '/projects/$project/data': typeof ProjectsProjectDataRoute
  '/projects/$project/fields': typeof ProjectsProjectFieldsRoute
  '/projects/$project/settings': typeof ProjectsProjectSettingsRoute
  '/projects/$project/users': typeof ProjectsProjectUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/api_keys': typeof Api_keysRoute
  '/branding': typeof BrandingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/users': typeof UsersRoute
  '/projects/$project': typeof ProjectsProjectRouteWithChildren
  '/task/$task': typeof TaskTaskRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$project/access': typeof ProjectsProjectAccessRoute
  '/projects/$project/dashboard': typeof ProjectsProjectDashboardRoute
  '/projects/$project/data': typeof ProjectsProjectDataRoute
  '/projects/$project/fields': typeof ProjectsProjectFieldsRoute
  '/projects/$project/settings': typeof ProjectsProjectSettingsRoute
  '/projects/$project/users': typeof ProjectsProjectUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/api_keys'
    | '/branding'
    | '/projects'
    | '/users'
    | '/projects/$project'
    | '/task/$task'
    | '/projects/'
    | '/projects/$project/access'
    | '/projects/$project/dashboard'
    | '/projects/$project/data'
    | '/projects/$project/fields'
    | '/projects/$project/settings'
    | '/projects/$project/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/api_keys'
    | '/branding'
    | '/users'
    | '/projects/$project'
    | '/task/$task'
    | '/projects'
    | '/projects/$project/access'
    | '/projects/$project/dashboard'
    | '/projects/$project/data'
    | '/projects/$project/fields'
    | '/projects/$project/settings'
    | '/projects/$project/users'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/api_keys'
    | '/branding'
    | '/projects'
    | '/users'
    | '/projects/$project'
    | '/task/$task'
    | '/projects/'
    | '/projects/$project/access'
    | '/projects/$project/dashboard'
    | '/projects/$project/data'
    | '/projects/$project/fields'
    | '/projects/$project/settings'
    | '/projects/$project/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  Api_keysRoute: typeof Api_keysRoute
  BrandingRoute: typeof BrandingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  UsersRoute: typeof UsersRoute
  TaskTaskRoute: typeof TaskTaskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_keys': {
      id: '/api_keys'
      path: '/api_keys'
      fullPath: '/api_keys'
      preLoaderRoute: typeof Api_keysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/task/$task': {
      id: '/task/$task'
      path: '/task/$task'
      fullPath: '/task/$task'
      preLoaderRoute: typeof TaskTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project': {
      id: '/projects/$project'
      path: '/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof ProjectsProjectRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$project/users': {
      id: '/projects/$project/users'
      path: '/users'
      fullPath: '/projects/$project/users'
      preLoaderRoute: typeof ProjectsProjectUsersRouteImport
      parentRoute: typeof ProjectsProjectRoute
    }
    '/projects/$project/settings': {
      id: '/projects/$project/settings'
      path: '/settings'
      fullPath: '/projects/$project/settings'
      preLoaderRoute: typeof ProjectsProjectSettingsRouteImport
      parentRoute: typeof ProjectsProjectRoute
    }
    '/projects/$project/fields': {
      id: '/projects/$project/fields'
      path: '/fields'
      fullPath: '/projects/$project/fields'
      preLoaderRoute: typeof ProjectsProjectFieldsRouteImport
      parentRoute: typeof ProjectsProjectRoute
    }
    '/projects/$project/data': {
      id: '/projects/$project/data'
      path: '/data'
      fullPath: '/projects/$project/data'
      preLoaderRoute: typeof ProjectsProjectDataRouteImport
      parentRoute: typeof ProjectsProjectRoute
    }
    '/projects/$project/dashboard': {
      id: '/projects/$project/dashboard'
      path: '/dashboard'
      fullPath: '/projects/$project/dashboard'
      preLoaderRoute: typeof ProjectsProjectDashboardRouteImport
      parentRoute: typeof ProjectsProjectRoute
    }
    '/projects/$project/access': {
      id: '/projects/$project/access'
      path: '/access'
      fullPath: '/projects/$project/access'
      preLoaderRoute: typeof ProjectsProjectAccessRouteImport
      parentRoute: typeof ProjectsProjectRoute
    }
  }
}

interface ProjectsProjectRouteChildren {
  ProjectsProjectAccessRoute: typeof ProjectsProjectAccessRoute
  ProjectsProjectDashboardRoute: typeof ProjectsProjectDashboardRoute
  ProjectsProjectDataRoute: typeof ProjectsProjectDataRoute
  ProjectsProjectFieldsRoute: typeof ProjectsProjectFieldsRoute
  ProjectsProjectSettingsRoute: typeof ProjectsProjectSettingsRoute
  ProjectsProjectUsersRoute: typeof ProjectsProjectUsersRoute
}

const ProjectsProjectRouteChildren: ProjectsProjectRouteChildren = {
  ProjectsProjectAccessRoute: ProjectsProjectAccessRoute,
  ProjectsProjectDashboardRoute: ProjectsProjectDashboardRoute,
  ProjectsProjectDataRoute: ProjectsProjectDataRoute,
  ProjectsProjectFieldsRoute: ProjectsProjectFieldsRoute,
  ProjectsProjectSettingsRoute: ProjectsProjectSettingsRoute,
  ProjectsProjectUsersRoute: ProjectsProjectUsersRoute,
}

const ProjectsProjectRouteWithChildren = ProjectsProjectRoute._addFileChildren(
  ProjectsProjectRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsProjectRoute: typeof ProjectsProjectRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectRoute: ProjectsProjectRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  Api_keysRoute: Api_keysRoute,
  BrandingRoute: BrandingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  UsersRoute: UsersRoute,
  TaskTaskRoute: TaskTaskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
